name: Auto Build Python Executable

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths: 
      - '**.py'             # 所有 Python 文件变化
      - 'requirements.txt'  # 依赖清单
      - 'img/**'            # 图标资源目录
      - '.github/workflows/**' # 工作流文件本身的变化
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # ─── 1. Checkout A 仓库本身的代码 ───────────────────────────────
      - name: Checkout A Repository
        uses: actions/checkout@v4

      # ─── 2. 设置 Python 环境 ────────────────────────────────────────
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # ─── 3. Checkout 私有仓库 B，并编译 Cython 扩展 ───────────────────
      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper        # ← 改成你真正的 “owner/B”
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (Linux)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if [ -f B/requirements.txt ]; then
            pip install -r B/requirements.txt
          fi

      - name: Build Cython extension from B (Linux)
        run: |
          cd B
          python setup.py build_ext --inplace
          cd ..

      - name: Copy compiled B extension into A's root (Linux)
        run: |
          # 假设 B 编译出的 Cython 模块名以 client_mod 开头，并且后缀是 .so
          cp B/client_mod.*.so . || true

      # ─── 4. 缓存 A 仓库的 pip 依赖 ────────────────────────────────────
      - name: Cache Dependencies (Linux)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ─── 5. 安装 A 仓库所需依赖（含 pyinstaller） ───────────────────────
      - name: Install Dependencies (Linux)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # ─── 6. 使用 PyInstaller 打包成可执行文件 ─────────────────────────
      - name: Build Executable (Linux)
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-${{ github.sha }}"
          fi

          # PyInstaller 会把与 main.py 同目录下的 .so 一并打包
          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-Linux_amd64-$VERSION \
            --clean \
            main.py

      # ─── 7. 上传产物 ────────────────────────────────────────────────
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/TomatoNovelDownloader-*

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm  # ARM64 架构
    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # ─── 3. Checkout 私有仓库 B，并编译 Cython 扩展 ───────────────────
      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper        # ← 改成你真正的 “owner/B”
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (Linux ARM64)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if [ -f B/requirements.txt ]; then
            pip install -r B/requirements.txt
          fi

      - name: Build Cython extension from B (Linux ARM64)
        run: |
          cd B
          python setup.py build_ext --inplace
          cd ..

      - name: Copy compiled B extension into A's root (Linux ARM64)
        run: |
          cp B/client_mod.*.so . || true

      # ─── 4. 缓存 A 仓库的 pip 依赖 ────────────────────────────────────
      - name: Cache Dependencies (Linux ARM64)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ─── 5. 安装 A 仓库所需依赖（含 pyinstaller） ───────────────────────
      - name: Install Dependencies (Linux ARM64)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # ─── 6. 使用 PyInstaller 打包成可执行文件 ─────────────────────────
      - name: Build Executable (Linux ARM64)
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-${{ github.sha }}"
          fi

          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-Linux_arm64-$VERSION \
            --clean \
            main.py

      # ─── 7. 上传产物 ────────────────────────────────────────────────
      - name: Upload Linux ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: dist/TomatoNovelDownloader-*
  
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # ─── 3. Checkout 私有仓库 B，并编译 Cython 扩展（Windows 环境） ─────
      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper        # ← 改成你真正的 “owner/B”
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if (Test-Path "B\\requirements.txt") {
            pip install -r B\\requirements.txt
          }
        shell: powershell

      - name: Build Cython extension from B (Windows)
        run: |
          cd B
          python setup.py build_ext --inplace
          cd ..
        shell: powershell

      - name: Copy compiled B extension into A's root (Windows)
        run: |
          # 假设 B 编译出的 Cython 模块名以 client_mod 开头，并且后缀是 .pyd
          Copy-Item "B\\client_mod*.pyd" "." -Force
        shell: powershell

      # ─── 4. 缓存 A 仓库的 pip 依赖 ────────────────────────────────────
      - name: Cache Dependencies (Windows)
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ─── 5. 安装 A 仓库所需依赖（含 pyinstaller） ───────────────────────
      - name: Install Dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: powershell

      - name: Download UPX (Windows)
        run: |
          $url = "https://github.com/upx/upx/releases/download/v5.0.0/upx-5.0.0-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile upx.zip
          Expand-Archive -Path upx.zip -DestinationPath upx
        shell: powershell

      # ─── 6. 使用 PyInstaller 打包成可执行文件 ─────────────────────────
      - name: Build Executable (Windows)
        run: |
          $upxDir = "$pwd\upx\upx-5.0.0-win64"
        
          if (Test-Path "$upxDir\upx.exe") {
              icacls "$upxDir\upx.exe" /grant Everyone:F
          }

          if ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $version = "sha-${{ github.sha }}"
          }
        
          pyinstaller --onefile `
            --upx-dir "$upxDir" `
            --collect-data fake_useragent `
            -i img/Tomato-downlaoder-ico.ico `
            --name=TomatoNovelDownloader-Win64-$version `
            --clean `
            main.py
        shell: powershell

      # ─── 7. 上传产物 ────────────────────────────────────────────────
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\TomatoNovelDownloader-*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # ─── 3. Checkout 私有仓库 B，并编译 Cython 扩展（macOS 环境） ────────
      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper        # ← 改成你真正的 “owner/B”
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (macOS)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if [ -f B/requirements.txt ]; then
            pip install -r B/requirements.txt
          fi

      - name: Build Cython extension from B (macOS)
        run: |
          cd B
          python setup.py build_ext --inplace
          cd ..

      - name: Copy compiled B extension into A's root (macOS)
        run: |
          cp B/client_mod.*.so . || true

      # ─── 4. 缓存 A 仓库的 pip 依赖 ────────────────────────────────────
      - name: Cache Dependencies (macOS)
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ─── 5. 安装 A 仓库所需依赖（含 pyinstaller） ───────────────────────
      - name: Install Dependencies (macOS)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # ─── 6. 使用 PyInstaller 打包成可执行文件 ─────────────────────────
      - name: Build Executable (macOS)
        run: |         
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-${{ github.sha }}"
          fi

          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-macOS_arm64-$VERSION \
            --clean \
            main.py

      # ─── 7. 上传产物 ────────────────────────────────────────────────
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/TomatoNovelDownloader-macOS_arm64-*

  publish-release:
    needs: [build-linux, build-linux-arm64, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List Artifacts
        run: ls -R release-artifacts
    
      - name: Generate Release Notes
        id: generate_notes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag = context.ref.replace('refs/tags/', '');
  
            // 1. 找到上一个 release
            const releasesResp = await github.rest.repos.listReleases({
              owner, repo, per_page: 100
            });
            const releases = releasesResp.data;
            const tags = releases.map(r => r.tag_name);
            const idx = tags.indexOf(tag);
            const prev = idx < releases.length - 1 ? releases[idx+1] : null;
            const since = prev ? prev.published_at : null;
            const prevTag = prev ? prev.tag_name : null;
  
            // 2. 生成 compare 链接
            const compareUrl = prevTag
              ? `https://github.com/${owner}/${repo}/compare/${prevTag}...${tag}`
              : '';
  
            // 3. 拉取自上一个 release 以来所有关闭的 issue/PR（已过滤 wontfix/duplicate）
            const params = { owner, repo, state: 'closed', per_page: 100 };
            if (since) params.since = since;
            const issuesResp = await github.rest.issues.listForRepo(params);
            const items = issuesResp.data.filter(item =>
              !item.labels.some(lbl => ['wontfix', 'duplicate'].includes(lbl.name.toLowerCase()))
            );
  
            // 4. 按标签分组
            const groups = { Fix: [], Update: [], Feature: [] };
            items.forEach(item => {
              item.labels.forEach(lbl => {
                if (lbl.name === 'bug')         groups.Fix.push(item);
                else if (lbl.name === 'update') groups.Update.push(item);
                else if (lbl.name === 'enhancement') groups.Feature.push(item);
              });
            });
  
            // 5. 构建 Markdown body
            let body = "# What's Changed\n\n";
            const zh = { Fix: '修复', Update: '更新', Feature: '新增' };
            for (const key of ['Fix','Update','Feature']) {
              if (groups[key].length) {
                body += `## ${key}\n\n`;
                for (const i of groups[key]) {
                  body += `- ${zh[key]}：[#${i.number}](${i.html_url}) ${i.title}\n`;
                }
                body += "\n";
              }
            }
            if (compareUrl) {
              body += `**Full Changelog**: ${compareUrl}\n`;
            }
  
            return body;
  
      - name: Create Unified Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Tomato Novel Downloader ${{ github.ref_name }}
          body: ${{ steps.generate_notes.outputs.result }}
          files: |
            release-artifacts/linux-build/TomatoNovelDownloader-Linux_amd64-*
            release-artifacts/linux-arm64-build/TomatoNovelDownloader-Linux_arm64-*
            release-artifacts/windows-build/TomatoNovelDownloader-Win64-*.exe
            release-artifacts/macos-build/TomatoNovelDownloader-macOS_arm64-*
