name: Auto Build Python Executable

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths: 
      - '**.py'          # 所有 Python 文件
      - 'requirements.txt' # 依赖清单
      - 'img/**'         # 图标资源目录
      - '.github/workflows/**' # GitHub Actions 工作流文件
  pull_request:

jobs:
  extract-termux-libs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: 安装解包工具
          run: |
            sudo apt-get update
            sudo apt-get install -y xz-utils binutils curl wget tar
  
        - name: 拉取 Termux aarch64 库
          shell: bash
          run: |
            mkdir -p termux-libs/usr/lib
            PKGS="openssl bzip2 xz libffi sqlite readline ncurses zlib util-linux"
            PACKAGES_URL="https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages.xz"
  
            # 1) 下载索引到本地
            curl -sL "$PACKAGES_URL" -o Packages.xz
            xzcat Packages.xz > Packages
  
            # 2) 依次解包每个 pkg
            for pkg in $PKGS; do
              echo "下载并解包 $pkg ..."
              URL=$(awk "/^Package: $pkg\$/,/^$/" Packages \
                    | grep '^Filename:' \
                    | awk '{print "https://packages-cf.termux.dev/apt/termux-main/" $2}')
              wget -q -O "${pkg}.deb" "$URL"
              ar x "${pkg}.deb" data.tar.xz
              tar -xf data.tar.xz -C termux-libs
            done
  
        - name: 拉取 Debian aarch64 glibc 核心库
          shell: bash
          run: |
            mkdir -p debian-rootfs
            curl -sL \
              https://deb.debian.org/debian/dists/stable/main/installer-arm64/current/images/netboot/debian-installer/arm64/rootfs.gz \
              | gunzip -c > rootfs.tar
            tar -xf rootfs.tar -C debian-rootfs
            for lib in libc.so.6 libdl.so.2 libpthread.so.0 libz.so.1 ld-linux-aarch64.so.1; do
              cp debian-rootfs/lib/aarch64-linux-gnu/$lib termux-libs/usr/lib/
            done
  
        - name: 上传 termux-libs 工件
          uses: actions/upload-artifact@v4
          with:
            name: termux-libs-aarch64
            path: termux-libs/usr/lib

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-${{ github.sha }}"
          fi

          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-Linux_amd64-$VERSION \
            --clean \
            main.py
      
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/TomatoNovelDownloader-*

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm  # 使用ARM64架构的运行器
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-${{ github.sha }}"
          fi

          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-Linux_arm64-$VERSION \
            --clean \
            main.py
      
      - name: Upload Linux ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: dist/TomatoNovelDownloader-*

  build-termux-arm64:
    needs: extract-termux-libs
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Download Termux+glibc 库
        uses: actions/download-artifact@v4
        with:
          name: termux-libs-aarch64
          path: termux-libs/usr/lib

      - name: Build Executable 并注入 so
        run: |
          # 版本号
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-${{ github.sha }}"
          fi

          # 拼接所有 so 的 --add-binary 参数
          SO_FLAGS=""
          for so in termux-libs/usr/lib/*.so*; do
            SO_FLAGS="$SO_FLAGS --add-binary $so:lib"
          done

          # 1) 先打包
          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-Termux_arm64-$VERSION \
            --clean \
            $SO_FLAGS \
            main.py

          # 2) 用 patchelf 修改 interpreter 与 rpath → 运行时优先加载解包后的 lib/
          patchelf --set-interpreter '$ORIGIN/lib/ld-linux-aarch64.so.1' \
                   --set-rpath '$ORIGIN/lib' \
                   dist/TomatoNovelDownloader-Termux_arm64-$VERSION

      - name: Upload Termux ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: termux-arm64-build
          path: dist/TomatoNovelDownloader-Termux_arm64-*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download UPX
        run: |
          $url = "https://github.com/upx/upx/releases/download/v5.0.0/upx-5.0.0-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile upx.zip
          Expand-Archive -Path upx.zip -DestinationPath upx

      - name: Build Executable
        run: |
          $upxDir = "$pwd\upx\upx-5.0.0-win64"
        
          if (Test-Path "$upxDir\upx.exe") {
              icacls "$upxDir\upx.exe" /grant Everyone:F
          }

          if ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $version = "sha-${{ github.sha }}"
          }
        
          pyinstaller --onefile `
            --upx-dir "$upxDir" `
            --collect-data fake_useragent `
            -i img/Tomato-downlaoder-ico.ico `
            --name=TomatoNovelDownloader-Win64-$version `
            --clean `
            main.py
      
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\TomatoNovelDownloader-*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |         
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-${{ github.sha }}"
          fi

          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-macOS_arm64-$VERSION \
            --clean \
            main.py

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/TomatoNovelDownloader-macOS_arm64-*

  publish-release:
    needs: [build-linux, build-linux-arm64, build-windows, build-macos, build-termux-arm64]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List Artifacts
        run: ls -R release-artifacts
    
      - name: Generate Release Notes
        id: generate_notes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag = context.ref.replace('refs/tags/', '');
  
            // 1. 找到上一个 release
            const releasesResp = await github.rest.repos.listReleases({
              owner, repo, per_page: 100
            });
            const releases = releasesResp.data;
            const tags = releases.map(r => r.tag_name);
            const idx = tags.indexOf(tag);
            const prev = idx < releases.length - 1 ? releases[idx+1] : null;
            const since = prev ? prev.published_at : null;
            const prevTag = prev ? prev.tag_name : null;
  
            // 2. 生成 compare 链接
            const compareUrl = prevTag
              ? `https://github.com/${owner}/${repo}/compare/${prevTag}...${tag}`
              : '';
  
            // 3. 拉取自上一个 release 以来所有关闭的 issue/PR（已过滤 wontfix/duplicate）
            const params = { owner, repo, state: 'closed', per_page: 100 };
            if (since) params.since = since;
            const issuesResp = await github.rest.issues.listForRepo(params);
            const items = issuesResp.data.filter(item =>
              !item.labels.some(lbl => ['wontfix', 'duplicate'].includes(lbl.name.toLowerCase()))
            );
  
            // 4. 按标签分组
            const groups = { Fix: [], Update: [], Feature: [] };
            items.forEach(item => {
              item.labels.forEach(lbl => {
                if (lbl.name === 'bug')         groups.Fix.push(item);
                else if (lbl.name === 'update') groups.Update.push(item);
                else if (lbl.name === 'enhancement') groups.Feature.push(item);
              });
            });
  
            // 5. 构建 Markdown body
            let body = "# What's Changed\n\n";
            const zh = { Fix: '修复', Update: '更新', Feature: '新增' };
            for (const key of ['Fix','Update','Feature']) {
              if (groups[key].length) {
                body += `## ${key}\n\n`;
                for (const i of groups[key]) {
                  body += `- ${zh[key]}：[#${i.number}](${i.html_url}) ${i.title}\n`;
                }
                body += "\n";
              }
            }
            if (compareUrl) {
              body += `**Full Changelog**: ${compareUrl}\n`;
            }
  
            return body;
  
      - name: Create Unified Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Tomato Novel Downloader ${{ github.ref_name }}
          body: ${{ steps.generate_notes.outputs.result }}
          files: |
            release-artifacts/linux-build/TomatoNovelDownloader-Linux_amd64-*
            release-artifacts/linux-arm64-build/TomatoNovelDownloader-Linux_arm64-*
            release-artifacts/windows-build/TomatoNovelDownloader-Win64-*.exe
            release-artifacts/macos-build/TomatoNovelDownloader-macOS_arm64-*
            release-artifacts/termux-arm64-build/TomatoNovelDownloader-Termux_arm64-*
